kind = "web"
previewPath = "/"
title = "ARIA Telegram Bot"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "ARIA Bot"
paths = ["/"]

[services.development]
run = "python babu/bot.py"

[services.production]

[services.production.run]
args = ["python", "babu/bot.py"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/healthz"
